---
title: "Week 1 notebook"
output: html_notebook
---

```{r}
#This is the script to solve Quiz 1


```


Questions from 11 to 20
```{r}

#Question 11 In the dataset provided for this Quiz, what are the column names of the dataset? 


#Read data

data <- read.csv("input/hw1_data.csv")

colnames(data)

#Question 12 Extract the first 2 rows of the data frame and print them to the console. What does the output look like?
head(data, 2)

#Question 13 How many observations (i.e. rows) are in this data frame?

nrow(data)

#Question 14 Extract the last 2 rows of the data frame and print them to the console. What does the output look like?
tail(data, 2)

#Question 15 What is the value of Ozone in the 47th row?

data[47,"Ozone"]

#Question 16 How many missing values are in the Ozone column of this data frame?

sum(is.na(data[,"Ozone"]))

#Quesiton 17 What is the mean of the Ozone column in this dataset? Exclude missing values (coded as NA) from this calculation.

ozone_na <- is.na(data[,"Ozone"])
mean(data[,"Ozone"][!ozone_na])

#Question 18 Extract the subset of rows of the data frame where Ozone values are above 31 and Temp values are above 90. What is the mean of Solar.R in this subset?

question_18 <- data[,"Ozone"]>31 & data[,"Temp"]>90 
mean(data[,"Solar.R"][question_18],na.rm = TRUE)

#Question 19 What is the mean of "Temp" when "Month" is equal to 6? 

question_19 <- data[,"Month"]==6
mean(data[,"Temp"][question_19],na.rm = TRUE)

#Question 20 What was the maximum ozone value in the month of May (i.e. Month is equal to 5)?

question_20 <- data[,"Month"]==5
max(data[,"Ozone"][question_20], na.rm = TRUE)



```

